### ISSUE TITLE
EnabledManager.getOrCreateSimon() is synchronized

### ISSUE THREAD

**Issue by DanielYWoo** [virgo47/javasimon#13]
This method is frequently called, each time a Stopwatch is requested, the threads will be blocked here. Can we narrow the scope of the lock? E,g. only lock the whole manager when allSimons.get(name) returns null.
```
private Simon getOrCreateSimon(String name, Class<? extends AbstractSimon> simonClass) {
	if (name == null) {
		// create an "anonymous" Simon - Manager does not care about it anymore
		return instantiateSimon(null, simonClass);
	}
	if (name.equals(ROOT_SIMON_NAME)) {
		throw new SimonException("Root Simon cannot be replaced or recreated!");
	}
	AbstractSimon simon = allSimons.get(name);
	if (simon != null && simonClass.isInstance(simon)) {
		return simon;
	} else {
		synchronized (this) {
			...........
		}
	}
	callback.onSimonCreated(simon);
	return simon;
}
```

Or can we use a StampLock or ReadWriteLock for this?

**Comment by virgo47** [comment]
I'd not go to `StampLocks` or `ReadWriteLocks` as I'm not familiar with them enough. Once I tried rework Stopwatches to read-write locks, it seemed to make sense, however I wasn't able to prove it. RW lock got better for some amount of threads while synchronized for different + was more consistent. So I rather stayed with much simpler solution in code.

Here I synchronized only the creation part itself, of course I had to re-check `allSimons.get(name)` again in the critical section. I think it's in alignment with the double-check locking paradigm. I'll release it when I have a bit more to release or after some time(out). :-) Thanks

**Comment by DanielYWoo** [comment]
Thanks!

**Comment by dalegaspi** [comment]
hi..i presume this is in the next release?  4.1.0 doesn't seem to have this fix.

**Comment by virgo47** [comment]
I didn't get to release this yet, but I'll look into it. I didn't consider it so critical, as it does not affect correctness. Probably will be out as 4.1.1 soon.

**Comment by dalegaspi** [comment]
thanks, Richard!  just to give you an idea of how this affects performance in our J2EE (Jersey REST) app...in a test with up to 1000 requests with up to 100 concurrent connections...the total time spent is ~122s and according to YourKit, about ~9.8s is spent on being blocked by `getOrCreateSimon`...IMO that's pretty significant no?

**Comment by virgo47** [comment]
I understand, I'll push it out soon. :-) I promise.

**Comment by virgo47** [comment]
Released today in 4.1.1

**Comment by dalegaspi** [comment]
Thank you!

**Comment by DanielYWoo** [comment]
wow, that's cool, thanks!
