### ISSUE TITLE
JDBC 4.2 Support (Java 8)

### ISSUE THREAD

**Issue by jimsimon** [virgo47/javasimon#17]
Please consider adding a proxy JDBC driver for version 4.2 (which is shipped with Java 8)

**Comment by virgo47** [comment]
I was thinking about it, but JDBC 4.1 works OK with Java 8 (unlike when you use JDBC 4.0 with Java 7 which just fails for not implementing the interface). Currently I'm not planning to implement Java 8 or JDBC 4.2 support explicitly. I'm open to pull requests though, but it would probably have to be new module in Java Simon 4.x line. Alternative is a new Java Simon 5.x branch targeted for Java 8, but I don't have time for this now.
