### ISSUE TITLE
AbstractSimon is not thread-safe ?

### ISSUE THREAD

**Issue by vlk32** [virgo47/javasimon#20]
Hi,
     
I use Javasimon in Spark+Drools application, and get undeterministic responses, 
some measurements are losts and not written to output. 

Could I ask class AbstractSimon should be thread-safe ?
If yes, please change incrementalSimons from HashMap to java.util.concurrent.ConcurrentHashMap.

thanks 

vlk

**Comment by virgo47** [comment]
After a review of the code I found some problems with the synchronization and I will look into it.

**Comment by virgo47** [comment]
Try fresh 4.1.3
