### ISSUE TITLE
Incorrect json escaping

### ISSUE THREAD

**Issue by alexandertokarev** [virgo47/javasimon#21]
org.javasimon.console.json.JsonStringifierFactory  currently escapes the following characters:

```
"\"" => "\\\""
"\\" =>  "\\\\"
"/" => "\\/"
```
But there are also some characters that require escaping: 

```
"\b" => "\\b"
"\n" => "\\n"
"\t" => "\\t"
"\f" => "\\f"
"\r" => "\\r"
```

Otherwise console is not working if a simon note  contains a new line character:

![screen shot 2018-03-13 at 11 46 58](https://user-images.githubusercontent.com/10973319/37331630-70a30486-26b5-11e8-827d-abedd9be04ac.png)

**Comment by virgo47** [comment]
Ouch, after months I decided to do something here and after I fixed it I see your pull request. :-) I used the test from it, but I'll push my changes. They do pass your modified test.
