### ISSUE TITLE
ConcurrentModificationException in ManagerConfiguration

### ISSUE THREAD

**Issue by Lcole** [virgo47/javasimon#28]
Have run into a CME in ManagerConfiguration.getConfig()
The configs (LinkedHashMap) is apparently updated by processSimon() while getConfig() is looping over the keyset

**Comment by virgo47** [comment]
I can see the problem. I'll add some synchronization there, but the whole config stuff hasn't been ever completely finished (TODOs in class javadoc). If you can avoid it, I'd recommend it.
I can't give you any timelines now, as Java Simon is not actively developed anymore - and frankly is probably beyond its horizon anyway.

**Comment by Lcole** [comment]
Mind if I fix it and provide the patch?

 

Lee Cole

 <mailto:leecole@gmail.com> leecole@gmail.com / +1 720-985-4716

**Comment by virgo47** [comment]
No, I don't mind. :-) And yes, I can release a patch version afterwards.
