### ISSUE TITLE
Simon.reset() deprecation

### ISSUE THREAD

**Issue by jeacott1** [virgo47/javasimon#36]
Hi all,
 I'm working through an old project I need to update, and have come across code of the ilk 
```
SimonManager.getSimon(name).reset();
```

I see the reset() method exists in 2.4, but is disappeared in 2.5, with no deprecation warning or advice on what replaces it that I can find.

can anyone advise for modern Simon what should replace this reset() functionality?

cheers

**Comment by virgo47** [comment]
Hi

It's mentioned in [release news for 3.5](https://github.com/virgo47/javasimon/blob/master/docs/History.md#350-released-2014-05-08), so I believe 3.5 is the version where they were deprecated, not sure whether removed right away.

But the point is to use incremental sampling with some key.
